# Introduction to Python

Welcome to the world of Python programming! Python is a versatile and powerful programming language that is easy to learn and fun to use.

This notebook discusses _basic data types and basic python operations_.


## Basic Data Types and Basic Python Operations

Python handles several types of expressions; e.g., string, numerical, list expressions, etc.

## Numerical Expression: Int vs Float



__Note:__ Statements following the pound symbol are not evaluated by Python. These are "comments" on your code. For example in the next cell I am adding numerical expression as a comment so you know what is the purpose of that cell. Including lots of comments in your code is very important for improving readability.

### Integer (int)

In [ ]:
#this is an int (integer)

2

In [ ]:
type(2)

int

For more reading, here is a link to the python 3 documentation on ints, https://docs.python.org/3/library/functions.html#int.

### Float

In [ ]:
#this is a float
2.0005

2.0005

In [ ]:
type(2.0005)

float

For more reading, here is a link to the python documentation for floats, https://docs.python.org/3/library/functions.html#float.



### Basic operations and basic function for numerical expressions

Python can perform all the basic arithmetic operations that you are familiar with from using a calculator. Let's explore some of these operations. Compute the following

In [ ]:
## add 2 and 3. What is the type of output?

In [ ]:
## subtract 2 from 3. What is the type of output?

In [ ]:
## devide 3 by 2. What is the type of output?

In [ ]:
## find the remainder of this devision. What is the type of output?

In [ ]:
## Raise 2 to the power of 10. What is the type of output?

**Exercise:**  use the following cell to evaluate $x^3 - 7x +178$ at $x =14$  

How do we take square root? or how to compute log? Let's try

In [ ]:
log(10)

NameError: name 'log' is not defined

Well we need to use a package (collection of functions written for specific tasks) to handel numerical computations and get access to this operations. This package is called `numpy` (numerical python). Let's import it:

In [ ]:
import numpy

In [ ]:
numpy.sqrt(10)

3.1622776601683795

In [ ]:
numpy.log(10)

2.302585092994046

Writting numpy everytime we want to compute something is a little inconviniece. For that reason, it is customary to import it as `np`:



In [ ]:
import numpy as np

In [ ]:
np.sqrt(10)

In [ ]:
np.log(10)

## String Expression and their operations
A python string is a piece of text like a word, sentence, or paragraph.

For more reading, here is the python documentation on strs, https://docs.python.org/3/library/stdtypes.html#textseq.

In [ ]:
'abcd' # String expression. Note the quotation marks.

'abcd'

In [ ]:
abcd # Without quotes, we get an error. Python wants to treat this as a variable (we learn this later).

In [ ]:
"abcd" # Double quotes also produces a string expression.

We can add two strings!

In [ ]:
'abcd'+'efgh' # Concatenation

'abcdefgh'

we can use `len()` function to find the length of a string

In [ ]:
len('abc')

3

we can use `print()` function to print more details:

In [ ]:
print(' the length of ', 'abc', 'is ', len('abc'))

 the length of  abc is  3


__Exercise:__ use concatenation to write down your first and last name. Also compute the number of letters in your name. Your output should be something like:

Soheyl Anbouhi,

The length of my name is = 13

Note that the `len()` function doesnt work for numbers

In [ ]:
len(200)

TypeError: object of type 'int' has no len()

However there is a cool function `str(x)` that converts the value $x$ to a string. This is useful when you need to ensure that a value is in string format, whether you're concatenating it with other strings, printing it, or performing operations that require strings.

In [ ]:
type(2.5)

float

In [ ]:
type(str(2.5))

str

In [ ]:
len(str(2.5))

3

In [ ]:
len(str(1234567))


7

__Exercise:__ find the number of digits in $2^{20}$

### Some useful built.in functions for strings

In [ ]:
## .lower(): lowers all the characters in the string

print("Soheyl Anbouhi".lower())

soheyl anbouhi


In [ ]:
## .upper() upper all the characters in the string

print("Soheyl Anbouhi".upper())

SOHEYL ANBOUHI


In [ ]:
## .replace() will replace substrings with other substrings
print("soheil Anbouhi.".replace("soheil", "Soheyl"))


Soheyl Anbouhi.


## List Expressions and their operations!

In [ ]:
[2,3,4,5] #A list expression whose elements are numerical expressions.

[2, 3, 4, 5]

In [ ]:
['a','b','c','defg'] # A list expression whose elements are string expressions.

['a', 'b', 'c', 'defg']

In [ ]:
['a',234] # Lists can contain different types of expressions.

In [ ]:
[['a','b','c'],[123],'1',2] # Lists can contain lists.

Lists are very important in our work. We can collect data in a list. Or define a vector or even a matrix using a list

In [ ]:
[1,2,3] # a vector in R^3. Although we are used to show a vector in vertical form, we can assume this is a horizontal vector

[1, 2, 3]

In [ ]:
 # a list of 2 column vectors, gives us a 2x3 matrix!
 [[1,2,3],[4,5,6]]

[[1, 2, 3], [4, 5, 6]]

#### List Operation
This is a little tricky. For example, if we add two vectors, we want them to be added component-wise. Let's see what happens if we do so:


In [ ]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

This works as concatenation not vector addition! So maybe a normal list is not good to define a vector. However, it works well for strings! For example, let's say you have a list of names, and want to add a new name

In [ ]:
['Sara', 'Soheyl'] + ['Tara']

['Sara', 'Soheyl', 'Tara']

In this course, we need to use a lot of vectors and matrices. How to define matrices and vectors then? We need a package that handeles numerical Python. Fortunately we have already imported this package: `numpy`.

In [ ]:
import numpy

Now we can define a vector as it follows"

In [ ]:
numpy.array([1,2,3]) #this tells the computer that [1,2,3] is not a normal list and it is turned into a numpy list

array([1, 2, 3])

Let's try addition now

In [ ]:
numpy.array([1,2,3]) + numpy.array([4,5,6])

array([5, 7, 9])

Looks good! How about a numpy arry of strigs? Let us try:

In [ ]:
numpy.array(['a','b','c'])

array(['a', 'b', 'c'], dtype='<U1')

Makes sense! Can we add them?

In [ ]:
numpy.array(['a','b','c']) + numpy.array(['cat','dog']) # This does not make sense!

We can use NumPy arrays to represent a matrix. Note that each list in the array represent a row of A.

In [ ]:
numpy.array([[1,2,3],[4,5,6]]) # A 2x3 matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
numpy.array([[1,2,3],[4,5,6]])+ numpy.array([[1,0,0],[0,0,0]]) # Matrices can be added

array([[2, 2, 3],
       [4, 5, 6]])

We will come back to matrices!

## Variables

In the operations above, we typed out the expression in each line. It is much more economical to store expressions in variables.

In [ ]:
# We define variable "a" and "b" to represent the number 2 and 3, resp.
a = 2
b = 3

In [ ]:
# We can now perform operations on the variables
a*b

6

In [ ]:
c = a**b # We can also define new variables by performing operations on the old ones

we can also use `print` to print the value of c

In [ ]:
print(c)

8


We can add a text to print for more clearity:

In [ ]:
print('The value of c is',c) ## note that there is a comma between the string and c

The value of c is 8


In [ ]:
#another example:

string1 = 'cat'
string2 = 'dog'
string1+string2

'catdog'

Virtually any string of numbers and letters can be used as a variable. Some symbols are reserved, however. For example, we can't use "2" to denote a variable.

In [ ]:
for = 5
# 'for' is reserved to denote a command in a 'for loop'. This will be discussed below.
# We get an error message if we attempt to use 'for' as a variable name.

SyntaxError: invalid syntax (<ipython-input-40-50d8479d7dac>, line 1)

In [ ]:
# Another example

L = ['a','b','c','d']

In [ ]:
L + ['e','f']

['a', 'b', 'c', 'd', 'e', 'f']

Variables can be redefined.

In [ ]:
a = 1
a = 2
print(a)

2


Variables can be redefined recursively.

In [ ]:
a = a+1
print(a)

3


In [ ]:
#Another Example
A = numpy.array([[3,2],[1,1]])
B = numpy.array([[2,2],[3,3]])
A + B

array([[5, 4],
       [4, 4]])