# Basic Pandas

In this notebook we learn about basics of DataFrame



First, we need to import the pandas library. It’s common practice to import pandas with the alias `pd`.


In [6]:
import numpy as np
import pandas as pd

## DataFrames

A DataFrame (DF) is a two-dimensional labeled data structure with columns of potentially different types. Think of it as a table or a spreadsheet. Many datasets are naturally represented as data frames. For example, CSV (Comma-Separated Values) files, Excel Sheets, SQL Database Tables and JSON Files.

### Creating a DF from a dictionaty or an array

You can create a DataFrame from a dictionary, list of dictionaries, or numpy arrays. A dictionary in Python is a collection of key-value pairs where each key is unique. You can think of a dictionary as a real-world dictionary where you look up a word (the key) to find its definition (the value).

In [7]:
#an example of numpy array
array_data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
##Creating a `DataFrame` from the numpy array:
df_from_array = pd.DataFrame(array_data, columns=['Column1', 'Column2', 'Column3'])
print(df_from_array)


   Column1  Column2  Column3
0        1        2        3
1        4        5        6
2        7        8        9


So you can see that DataFrame are more organized and we will see that they are easy to work with!

In [54]:
# Example of a dictionary

data = {'Name': ['Soheyl','Anthony', 'Bob', 'Charlie', 'Sara', 'John', 'Melisa', 'Wanchan'],
        'Age': [10, 25, 30, 35, 24, 16, 25, 22 ],
        'City': ['Asheville', 'Charlotte', 'New York', 'Los Angeles', 'Chicago', 'Tallahassee', 'Philly', 'Cullowhee']}
print(data)

{'Name': ['Soheyl', 'Anthony', 'Bob', 'Charlie', 'Sara', 'John', 'Melisa', 'Wanchan'], 'Age': [10, 25, 30, 35, 24, 16, 25, 22], 'City': ['Asheville', 'Charlotte', 'New York', 'Los Angeles', 'Chicago', 'Tallahassee', 'Philly', 'Cullowhee']}


In [55]:
# Creating a DataFrame from a dictionary
# Note that all lists must be of the same length
df = pd.DataFrame(data)
print(df)

      Name  Age         City
0   Soheyl   10    Asheville
1  Anthony   25    Charlotte
2      Bob   30     New York
3  Charlie   35  Los Angeles
4     Sara   24      Chicago
5     John   16  Tallahassee
6   Melisa   25       Philly
7  Wanchan   22    Cullowhee


### Exploring a DataFrame
Once you have a DataFrame, you can explore it using various methods.

In [33]:
# Viewing the first 4
df.head(4)

Name  Age         City
0   Soheyl   10    Asheville
1  Anthony   25    Charlotte
2      Bob   30     New York
3  Charlie   35  Los Angeles

In [29]:
## What does df.sample() do?

In [37]:
df.sample(5)

Name  Age         City
1  Anthony   25    Charlotte
6   Melisa   25       Philly
3  Charlie   35  Los Angeles
4     Sara   24      Chicago
5     John   16  Tallahassee

In [53]:
# Getting the summary of the DataFrame
print(df.info())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    8 non-null      object
 1   Age     8 non-null      int64 
 2   Salary  8 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 320.0+ bytes
None


Don't pass too soon. Take a moment and try to make sense out of the outcome.

In [40]:
# Descriptive statistics
## Note that it only gives a summary of numerical data
print(df.describe())

             Age
count   8.000000
mean   23.375000
std     7.744814
min    10.000000
25%    20.500000
50%    24.500000
75%    26.250000
max    35.000000


### Selecting Data in a DF
Sometimes you need to work on specific feature (column in your DataFrame). So you might be able to select tha pring that column. Here is how:

Run the following and try to figure out what they do and what are their differences.  

In [41]:
# Selecting a single column
print(df['Name'])

0     Soheyl
1    Anthony
2        Bob
3    Charlie
4       Sara
5       John
6     Melisa
7    Wanchan
Name: Name, dtype: object


In [43]:
# Selecting multiple columns
print(df[['Name', 'Age']])



      Name  Age
0   Soheyl   10
1  Anthony   25
2      Bob   30
3  Charlie   35
4     Sara   24
5     John   16
6   Melisa   25
7  Wanchan   22


In [44]:
# Selecting rows by label (index)
print(df.loc[0])

Name       Soheyl
Age            10
City    Asheville
Name: 0, dtype: object


In [45]:
# Selecting rows by position
print(df.iloc[0:2])

      Name  Age       City
0   Soheyl   10  Asheville
1  Anthony   25  Charlotte


### Filtering Data in a DF

Let's say you wanna access inside of table and select specifc parts of it. For example, maybe you are only interested in Age column
`



In [47]:
# Filtering rows where Age > 25
print(df[df['Age'] > 25])


      Name  Age         City
2      Bob   30     New York
3  Charlie   35  Los Angeles


### Adding/Removing Columns in a DF

In [56]:
# Adding a new column
df['Salary'] = [500000, 60000, 70000,10000, 300000, 1100000, 780000, 40000 ]
print(df)

      Name  Age         City   Salary
0   Soheyl   10    Asheville   500000
1  Anthony   25    Charlotte    60000
2      Bob   30     New York    70000
3  Charlie   35  Los Angeles    10000
4     Sara   24      Chicago   300000
5     John   16  Tallahassee  1100000
6   Melisa   25       Philly   780000
7  Wanchan   22    Cullowhee    40000


In [57]:
# Removing a column
#df = df.drop('City', axis=1)
#print(df)


### Adding values to a DF

sometimes you need to add an entry to your data set. For example, let's add `Ahora` to the list. They are 27 and from Texas but we dont know their salary.



In [83]:
## Adding a new entry by creating a new DataFrame and concatenating it with the existing one

### Create a new DataFrame with the new entry
new_entry = pd.DataFrame({
    'Name': ['Ahora'],
    'Age': [27],
    'City': ['Texas'],
    'Salary': [np.nan]
})

### Adding the new entry
new_df = pd.concat([df, new_entry], ignore_index=True)

print(df)

      Name  Age         City     Salary
0   Soheyl   10    Asheville   500000.0
1  Anthony   25    Charlotte    60000.0
2      Bob   30     New York    70000.0
3  Charlie   35  Los Angeles    10000.0
4     Sara   24      Chicago   300000.0
5     John   16  Tallahassee  1100000.0
6   Melisa   25       Philly   780000.0
7  Wanchan   22    Cullowhee    40000.0
8    Ahora   27        Texas        NaN


### Handeling missing information in a DF

In general working with dataset with missing information is challenging. You can try approximate the missing values or simply remove them. In Pandas we use `.fillna()`  to fill the empty entry or `.dropna()`to remove it.

In [92]:
# Create a copy of new_df to fill
Filled_df = new_df.copy()

print(Filled_df)


      Name  Age         City     Salary
0   Soheyl   10    Asheville   500000.0
1  Anthony   25    Charlotte    60000.0
2      Bob   30     New York    70000.0
3  Charlie   35  Los Angeles    10000.0
4     Sara   24      Chicago   300000.0
5     John   16  Tallahassee  1100000.0
6   Melisa   25       Philly   780000.0
7  Wanchan   22    Cullowhee    40000.0
8    Ahora   27        Texas        NaN
9    Ahora   27        Texas        NaN


In [93]:
# Computing the mean of the Age column from df

mean_salary = df['Salary'].mean()

# Fill missing values with mean value in the Salary column
Filled_df['Salary'] = Filled_df['Salary'].fillna(mean_salary)

# Print the filled DataFrame
Filled_df

Name  Age         City     Salary
0   Soheyl   10    Asheville   500000.0
1  Anthony   25    Charlotte    60000.0
2      Bob   30     New York    70000.0
3  Charlie   35  Los Angeles    10000.0
4     Sara   24      Chicago   300000.0
5     John   16  Tallahassee  1100000.0
6   Melisa   25       Philly   780000.0
7  Wanchan   22    Cullowhee    40000.0
8    Ahora   27        Texas   357500.0
9    Ahora   27        Texas   357500.0

In [94]:
# You code
#Start with new_df that has missing values. Use drop.na to remove thoes rows with nan values



### Reading and Writing using Pandas

Pandas can read from and write to various file formats like CSV, Excel, and SQL databases. Here is how to read it:

In [21]:
# Reading data from a CSV file
#df = pd.read_csv('name.csv')
#print(df.head())

**Exercise** Exploring and Analyzing the Baseball Dataset
Objective:

Download the baseball dataset, explore its structure, handle missing information, and visualize specific columns to understand their relationships.

__Steps:__

1. **Download the Baseball CSV file**: You'll find the file on Canvas, located right next to this Jupyter Notebook (JNB) you're working on. Download it to your computer.

2. **Read the Dataset**:

   - **If you're using a local environment (e.g., Anaconda)**:
     - Ensure that the CSV file is saved in the same directory as your Jupyter Notebook. This way, the code provided (`pd.read_csv('name.csv')`) will work without any changes.
     - If your CSV file is saved in a different location, you'll need to provide the full file path in the `pd.read_csv()` function. For example, if your file is in a folder called "data," you would use `pd.read_csv('data/name.csv')` so pandas can locate the file.

   - **If you're using Google Colab**:
     - Upload the CSV file to the Files section on the left sidebar in Colab. You can do this by dragging and dropping the file into the Files section.
     - Once the file is uploaded, you can read it into your notebook using `pd.read_csv('name.csv')`.


 3. __Describe your dataset:__ what are the columns? Use .head() to get an overview of your data set.

 4. __Explore the Dataset:__

  - Use .info() to check the structure of the DataFrame, including column names and data types.

  - Use .describe() to get a statistical summary of numerical columns.     
  Don't pass too soon. Read it underestand it and try to interpret it.

5. __Handle Missing Information__: You can use fillna or dropna.It's your choice. But add a description why you believe one is better the other. If you have no idea explore both.


6. __Select Specific Columns__ In one of our upcoming labs, we will focus on only two columns from this dataset. To prepare for that, extract the columns related to "Wins" and "Total Runs" now.


7. __Plot the selected columns__: Use matplotlib or seaborn to plot the selected columns to visualize their relationship.
Provide a brief description of your observations from the plot.
